### ISSUE TITLE
Documentation is missing important information

### ISSUE THREAD

**Issue by ghost** [ddiiwoong/synology-prometheus#1]
I have not used snmp in depth, but I am trying to use your awesome tool here and I can't seem to get things wired correctly.  

First, some questions in the config file.
1. I believe this is the scrape endpoint for prometheus. https://github.com/ddiiwoong/synology-prometheus/blob/164ccafd5586bd60c388aca3f7b503fa20c2166e/config/prometheus.yml#L24  I don't see a port in this example, but this doesn't run on port 80 by default.  I am assuming a port needs to be declared here.
2. I am also assuming that the snmp exporter services is using the request data from Prometheus to make a call to the synology nas. https://github.com/ddiiwoong/synology-prometheus/blob/164ccafd5586bd60c388aca3f7b503fa20c2166e/config/prometheus.yml#L34  This has a comment around that this IP:Port needs to be the IP and port of the Synology NAS.  Does this support UDP?  Also, by default Synology NAS uses UDP and port 161, which confused me a bit.  Can you clarify?  
 
I am looking forward to getting this to work.  Thanks for your help.

**Comment by ddiiwoong** [comment]
Thank you for the issue.

https://github.com/ddiiwoong/synology-prometheus/blob/164ccafd5586bd60c388aca3f7b503fa20c2166e/config/prometheus.yml#L34

The config you mentioned is not the snmp port of synology, but the container port exposed by the snmp-exporter.

https://github.com/ddiiwoong/synology-prometheus/blob/164ccafd5586bd60c388aca3f7b503fa20c2166e/docker-compose.yml#L47-L53
