### ISSUE TITLE
Directory "snmp_exporter" does not exist.

### ISSUE THREAD

**Issue by koonfoon** [ddiiwoong/synology-prometheus#4]
Hi, I recently had forked and apply your repo to my synology nas. But when I run ```docker-compose up```, it gave me error something like ```directory "snmp_exporter" does not exist.``` .
After I changed ```./snmp_exporter/:/etc/snmp_exporter/``` to ```./snmp_synology/:/etc/snmp_exporter/``` (docker-compose.yml on line 52). It work perfectly.
Maybe you have your reason for binding the volumes as you did. But I thought I just let you know. Thanks  👍

**Comment by ddiiwoong** [comment]
Thank for your feedback. I changed snmp_exporter config directory path.
